/**
 * Documents the intent and loading expectations for every mobile route.
 *
 * This file is intentionally descriptive so future contributors can understand
 * what each screen is supposed to do before changing implementation details.
 */
export const ROUTE_META = {
  startup: {
    purpose: 'Bootstraps the app, restores token state, and redirects safely.',
    params: 'none',
    dataModel: 'local session snapshot + optional profile/wallet refresh',
    errors: 'falls back to guest mode and continues to home',
    empty: 'not applicable',
    auth: 'guest or restoring',
  },
  home: {
    purpose: 'Primary discovery entry with explore blocks and latest chapters.',
    params: 'none',
    dataModel: 'home dashboard payload',
    errors: 'shows retryable error state',
    empty: 'empty discovery state',
    auth: 'optional',
  },
  typeList: {
    purpose: 'Lists content by selected type such as manga or novel.',
    params: 'type',
    dataModel: 'paginated `/content/type/{type}` list',
    errors: 'shows retryable error state',
    empty: 'empty list state',
    auth: 'optional',
  },
  contentDetail: {
    purpose: 'Shows content summary plus chapter list and access actions.',
    params: 'type, slug',
    dataModel: 'detail payload + paginated chapter list',
    errors: 'shows blocking error state',
    empty: 'empty chapter state',
    auth: 'optional',
  },
  reader: {
    purpose: 'Reads a chapter using either text or image mode.',
    params: 'type, slug, chapterNumber',
    dataModel: 'chapter detail payload with access and adjacent chapters',
    errors: 'shows blocking reader error',
    empty: 'empty content state for malformed chapter data',
    auth: 'optional',
  },
  login: {
    purpose: 'Authenticates a mobile user with bearer-token-first flow.',
    params: 'none',
    dataModel: 'form submit',
    errors: 'inline form error',
    empty: 'not applicable',
    auth: 'guest',
  },
  register: {
    purpose: 'Creates a new account and transitions into login flow.',
    params: 'none',
    dataModel: 'form submit',
    errors: 'inline form error',
    empty: 'not applicable',
    auth: 'guest',
  },
  profile: {
    purpose: 'Shows the current user profile and quick account actions.',
    params: 'none',
    dataModel: 'private profile + store session',
    errors: 'guard or retryable error',
    empty: 'guest guard',
    auth: 'required',
  },
  library: {
    purpose: 'Shows followed content entries.',
    params: 'none',
    dataModel: 'paginated follows list',
    errors: 'guard or retryable error',
    empty: 'empty library state',
    auth: 'required',
  },
  history: {
    purpose: 'Shows recent reading progress/history.',
    params: 'none',
    dataModel: 'paginated history list',
    errors: 'guard or retryable error',
    empty: 'empty history state',
    auth: 'required',
  },
  wallet: {
    purpose: 'Shows wallet summary, transactions, and informational shop items.',
    params: 'none',
    dataModel: 'wallet summary + packages + features + transactions',
    errors: 'guard or retryable error',
    empty: 'empty transaction state',
    auth: 'required',
  },
  notifications: {
    purpose: 'Shows notification feed and read actions.',
    params: 'none',
    dataModel: 'notification list',
    errors: 'guard or retryable error',
    empty: 'empty notifications state',
    auth: 'required',
  },
  settings: {
    purpose: 'Edits app and reader preferences, manages logout.',
    params: 'none',
    dataModel: 'local store state + optional backend sync',
    errors: 'guard or retryable error',
    empty: 'not applicable',
    auth: 'required',
  },
};
