UPDATE taxonomies
SET ui_config = NULL
WHERE ui_config IS NOT NULL
  AND (TRIM(ui_config) = '' OR JSON_VALID(ui_config) = 0);

ALTER TABLE taxonomies
    MODIFY COLUMN ui_config JSON DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

UPDATE taxonomies
SET ui_config = JSON_SET(
    COALESCE(NULLIF(ui_config, ''), JSON_OBJECT()),
    '$.description',
    CASE slug
        WHEN 'game-system' THEN 'Oyun mekaniklerinin gerçek dünyaya taşındığı; görev, seviye ve ödül sistemleriyle ilerleyen serileri keşfedin.'
        WHEN 'system' THEN 'Görevler, ödüller ve karakter gelişimini yöneten özel bir sistem etrafında ilerleyen serileri keşfedin.'
        WHEN 'leveling' THEN 'Karakterlerin deneyim kazanıp seviye atlayarak yeni yeteneklere ulaştığı gelişim odaklı serileri keşfedin.'
        WHEN 'level-up' THEN 'Ana karakterin seviye atlayıp yeni güçler kazanarak sınırlarını aştığı gelişim serilerini keşfedin.'
        WHEN 'skill-system' THEN 'Yetenek ağaçları, özel beceriler ve karakter gelişim sistemlerinin hikâyenin merkezinde olduğu serileri keşfedin.'
        WHEN 'status-window' THEN 'Karakter özelliklerinin durum pencereleri ve sayısal değerlerle gösterildiği oyun sistemli serileri keşfedin.'
        WHEN 'dungeon' THEN 'Tehlikeli zindanlar, güçlü canavarlar ve değerli ödüller çevresinde şekillenen maceraları keşfedin.'
        WHEN 'tower' THEN 'Her katında yeni sınavlar ve rakipler bulunan gizemli kulelerde geçen yükseliş hikâyelerini keşfedin.'
        WHEN 'raid' THEN 'Takımların güçlü bosslara ve büyük tehditlere karşı birlikte mücadele ettiği aksiyon serilerini keşfedin.'
        WHEN 'op-protagonist' THEN 'Rakiplerinin çok ötesinde güce sahip ana karakterlerin sürükleyici mücadelelerini keşfedin.'
        WHEN 'overpowered-mc' THEN 'Olağanüstü gücüyle rakiplerine üstünlük kuran ana karakterlerin aksiyon dolu hikâyelerini keşfedin.'
        WHEN 'genius-mc' THEN 'Zekâsı, stratejisi veya sıra dışı yeteneğiyle öne çıkan dahi ana karakterlerin hikâyelerini keşfedin.'
        WHEN 'weak-to-strong' THEN 'Zayıf başlayan karakterlerin emek, eğitim ve mücadeleyle zirveye ulaştığı gelişim hikâyelerini keşfedin.'
        WHEN 'regression' THEN 'Geçmişe dönerek hatalarını düzeltmeye ve geleceği değiştirmeye çalışan karakterlerin hikâyelerini keşfedin.'
        WHEN 'reincarnation' THEN 'Yeni bir yaşamda farklı bir kimlik ve güçle yeniden doğan karakterlerin maceralarını keşfedin.'
        WHEN 'time-travel' THEN 'Zaman yolculuğu, değişen gelecekler ve geçmişe müdahale temalarını işleyen serileri keşfedin.'
        WHEN 'second-chance' THEN 'Hayatını yeniden kurma fırsatı bulan karakterlerin seçimlerini ve dönüşümünü anlatan serileri keşfedin.'
        WHEN 'transmigration' THEN 'Başka bir dünyaya, bedene veya hikâyeye geçen karakterlerin uyum ve hayatta kalma maceralarını keşfedin.'
        WHEN 'isekai' THEN 'Kahramanların farklı dünyalara taşındığı fantastik macera, keşif ve gelişim hikâyelerini keşfedin.'
        WHEN 'cultivation' THEN 'Ruhsal enerji, dövüş teknikleri ve uzun bir güçlenme yolculuğu üzerine kurulu serileri keşfedin.'
        WHEN 'murim' THEN 'Dövüş klanları, ustalar ve kadim tekniklerle şekillenen Murim dünyasındaki mücadeleleri keşfedin.'
        WHEN 'martial-arts-tag' THEN 'Dövüş teknikleri, disiplin ve ustalık yolculuklarıyla öne çıkan serileri keşfedin.'
        WHEN 'swordsmanship' THEN 'Kılıç ustalığı, düellolar ve savaş tekniklerinin öne çıktığı aksiyon dolu serileri keşfedin.'
        WHEN 'necromancer' THEN 'Ölüleri yöneten, ruhlarla bağ kuran veya karanlık büyüler kullanan karakterlerin hikâyelerini keşfedin.'
        WHEN 'assassin' THEN 'Gizlilik, suikast görevleri ve ölümcül beceriler etrafında gelişen gerilimli serileri keşfedin.'
        WHEN 'magic-academy' THEN 'Büyü eğitimi, akademi rekabeti ve genç büyücülerin gelişimini konu alan serileri keşfedin.'
        WHEN 'summoner' THEN 'Yaratıkları veya ruhları çağırarak savaşan karakterlerin fantastik maceralarını keşfedin.'
        WHEN 'tamer' THEN 'Canavarları evcilleştiren ve onlarla güçlü bağlar kuran karakterlerin serilerini keşfedin.'
        WHEN 'alchemy' THEN 'İksirler, dönüşüm sanatı ve gizemli formüllerin hikâyede önemli yer tuttuğu serileri keşfedin.'
        WHEN 'blacksmith' THEN 'Silah ve ekipman üreten ustaların zanaat, gelişim ve macera hikâyelerini keşfedin.'
        WHEN 'demons' THEN 'İblisler, şeytani güçler ve karanlık dünyalar çevresinde gelişen fantastik serileri keşfedin.'
        WHEN 'angels' THEN 'Melekler, kutsal güçler ve göksel çatışmaları konu alan fantastik serileri keşfedin.'
        WHEN 'gods' THEN 'Tanrılar, ilahi güçler ve ölümlülerin kaderini etkileyen mitolojik hikâyeleri keşfedin.'
        WHEN 'dragons' THEN 'Ejderhaların, kadim güçlerin ve efsanevi savaşların öne çıktığı fantastik serileri keşfedin.'
        WHEN 'monsters' THEN 'Canavarlarla mücadele, bilinmeyen yaratıklar ve tehlikeli dünyalar üzerine kurulu serileri keşfedin.'
        WHEN 'vampires' THEN 'Vampirler, ölümsüzlük ve karanlık ilişkiler etrafında gelişen doğaüstü hikâyeleri keşfedin.'
        WHEN 'werewolves' THEN 'Kurt adamlar, dönüşüm ve sürü bağlarını konu alan doğaüstü serileri keşfedin.'
        WHEN 'survival' THEN 'Zorlu koşullarda kaynak bulma, tehlikelerden kaçma ve hayatta kalma mücadelesini anlatan serileri keşfedin.'
        WHEN 'revenge' THEN 'Geçmişteki haksızlıkların hesabını sormaya çalışan karakterlerin intikam hikâyelerini keşfedin.'
        WHEN 'betrayal' THEN 'İhanetin karakterleri ve olayların yönünü değiştirdiği dramatik, gerilimli serileri keşfedin.'
        WHEN 'political' THEN 'İktidar mücadeleleri, entrikalar ve diplomatik çatışmalarla ilerleyen serileri keşfedin.'
        WHEN 'kingdom-building' THEN 'Bir bölgeyi veya krallığı sıfırdan geliştirip yöneten karakterlerin stratejik hikâyelerini keşfedin.'
        WHEN 'empire' THEN 'İmparatorlukların yükselişi, yönetim mücadeleleri ve büyük siyasi çatışmaları konu alan serileri keşfedin.'
        WHEN 'war' THEN 'Ordular, cepheler ve savaşın karakterler üzerindeki etkisini anlatan aksiyon ve dram serilerini keşfedin.'
        WHEN 'post-apocalyptic' THEN 'Felaket sonrası dünyalarda hayatta kalmaya ve yeniden düzen kurmaya çalışan karakterlerin hikâyelerini keşfedin.'
        WHEN 'magic' THEN 'Büyü sistemleri, büyücüler ve doğaüstü güçlerle şekillenen fantastik serileri keşfedin.'
        WHEN 'elemental-powers' THEN 'Ateş, su, toprak ve hava gibi elementleri kontrol eden karakterlerin maceralarını keşfedin.'
        WHEN 'superpowers' THEN 'Sıra dışı yeteneklere sahip karakterlerin çatışma, sorumluluk ve gelişim hikâyelerini keşfedin.'
        WHEN 'system-admin' THEN 'Kuralları yöneten veya sistem üzerinde özel yetkiye sahip karakterlerin hikâyelerini keşfedin.'
        WHEN 'virtual-reality' THEN 'Sanal dünyalar ile gerçek hayat arasındaki sınırları konu alan teknoloji odaklı serileri keşfedin.'
        WHEN 'vrmmo' THEN 'Sanal gerçeklik tabanlı çevrim içi oyunlarda geçen rekabet ve macera serilerini keşfedin.'
        WHEN 'video-games' THEN 'Video oyunları, oyuncu kültürü ve dijital dünyalarda geçen rekabetçi serileri keşfedin.'
        WHEN 'love-triangle' THEN 'Üç kişi arasındaki duygusal seçimler ve çatışmalar çevresinde gelişen romantik serileri keşfedin.'
        WHEN 'slow-burn' THEN 'Duygusal yakınlığın zaman içinde doğal ve yavaş biçimde geliştiği romantik hikâyeleri keşfedin.'
        WHEN 'enemies-to-lovers' THEN 'Çatışmayla başlayan ilişkilerin zamanla aşka dönüştüğü romantik serileri keşfedin.'
        WHEN 'childhood-friends' THEN 'Çocukluktan gelen bağların dostluk ve aşka dönüştüğü sıcak hikâyeleri keşfedin.'
        WHEN 'contract-marriage' THEN 'Bir anlaşmayla başlayan evliliğin beklenmedik duygulara dönüştüğü romantik serileri keşfedin.'
        WHEN 'marriage-of-convenience' THEN 'Çıkar veya zorunluluk nedeniyle kurulan evliliklerin değişen ilişkilerini anlatan serileri keşfedin.'
        WHEN 'harem' THEN 'Ana karakterin çevresinde birden fazla romantik ilginin yer aldığı ilişki odaklı serileri keşfedin.'
        WHEN 'reverse-harem' THEN 'Kadın ana karakterin çevresinde birden fazla romantik ilginin bulunduğu serileri keşfedin.'
        WHEN 'dark-fantasy' THEN 'Karanlık atmosfer, ahlaki ikilemler ve acımasız fantastik dünyalar sunan serileri keşfedin.'
        WHEN 'tragedy' THEN 'Kayıp, fedakârlık ve kaçınılmaz sonuçlar üzerine kurulu etkileyici dramatik serileri keşfedin.'
        WHEN 'psychological-trauma' THEN 'Travmanın karakterlerin kararları ve ilişkileri üzerindeki etkisini işleyen derinlikli serileri keşfedin.'
        WHEN 'mind-games' THEN 'Zekâ savaşları, manipülasyon ve stratejik hamlelerle ilerleyen gerilimli serileri keşfedin.'
        WHEN 'antihero' THEN 'Ahlaki açıdan gri seçimler yapan kusurlu ve sıra dışı ana karakterlerin hikâyelerini keşfedin.'
        WHEN 'villain-protagonist' THEN 'Hikâyeyi kötü karakterin bakış açısından anlatan karanlık ve alışılmadık serileri keşfedin.'
        WHEN 'school-life' THEN 'Okul yaşamı, arkadaşlıklar ve gençlik deneyimleri çevresinde gelişen serileri keşfedin.'
        WHEN 'academy' THEN 'Akademi eğitimi, rekabet ve öğrencilerin gelişim yolculuğunu anlatan serileri keşfedin.'
        WHEN 'office-romance' THEN 'İş hayatında başlayan ilişkileri ve profesyonel çatışmaları konu alan romantik serileri keşfedin.'
        WHEN 'age-gap' THEN 'Karakterler arasındaki yaş farkının ilişki dinamiklerinde önemli olduğu romantik hikâyeleri keşfedin.'
        WHEN 'gender-bender' THEN 'Cinsiyet değişimi veya farklı kimlik deneyimleri üzerinden ilerleyen serileri keşfedin.'
        WHEN 'crossdressing' THEN 'Kılık değiştirme ve farklı bir kimlikle yaşamanın doğurduğu durumları konu alan serileri keşfedin.'
        WHEN 'mecha-combat' THEN 'Dev robotlar ve ileri teknoloji savaş makineleriyle yapılan mücadeleleri konu alan serileri keşfedin.'
        WHEN 'military-strategy' THEN 'Taktik planlar, ordu yönetimi ve savaş stratejileriyle öne çıkan serileri keşfedin.'
        WHEN 'space-opera' THEN 'Galaksiler arası yolculuklar, büyük çatışmalar ve uygarlıklar sunan bilim kurgu serilerini keşfedin.'
        WHEN 'cyberpunk-elements' THEN 'Yüksek teknoloji, şirket egemenliği ve karanlık gelecek temalarını işleyen serileri keşfedin.'
        WHEN 'ai' THEN 'Yapay zekâ, bilinç ve insan-teknoloji ilişkisini konu alan bilim kurgu serilerini keşfedin.'
        WHEN 'robots' THEN 'Robotlar, androidler ve makinelerle insanlar arasındaki ilişkileri anlatan serileri keşfedin.'
        WHEN 'cooking' THEN 'Yemek hazırlama, mutfak kültürü ve lezzet yolculuklarını konu alan keyifli serileri keşfedin.'
        WHEN 'crafting' THEN 'Üretim, eşya geliştirme ve ustalık becerileriyle ilerleyen macera serilerini keşfedin.'
        WHEN 'farming' THEN 'Tarım, sakin yaşam ve üretim üzerine kurulu huzurlu gelişim hikâyelerini keşfedin.'
        WHEN 'merchant' THEN 'Ticaret, pazarlık ve ekonomik stratejiyle yükselen karakterlerin hikâyelerini keşfedin.'
        WHEN 'healer' THEN 'İyileştirme gücü ve destek yetenekleriyle ekibini ayakta tutan karakterlerin serilerini keşfedin.'
        ELSE CONCAT(name, ' temasını içeren manga, manhwa, webtoon ve novel serilerini keşfedin.')
    END
)
WHERE type = 'tag'
  AND (
      JSON_EXTRACT(COALESCE(NULLIF(ui_config, ''), JSON_OBJECT()), '$.description') IS NULL
      OR JSON_UNQUOTE(JSON_EXTRACT(COALESCE(NULLIF(ui_config, ''), JSON_OBJECT()), '$.description')) = ''
  );

UPDATE taxonomies
SET ui_config = JSON_SET(
    COALESCE(NULLIF(ui_config, ''), JSON_OBJECT()),
    '$.description',
    COALESCE(
        NULLIF(JSON_UNQUOTE(JSON_EXTRACT(COALESCE(NULLIF(ui_config, ''), JSON_OBJECT()), '$.description')), ''),
        CASE slug
            WHEN 'action' THEN 'Yoğun çatışmalar, hızlı tempolu mücadeleler ve güçlü rakiplerle ilerleyen aksiyon serilerini keşfedin.'
            WHEN 'adventure' THEN 'Yeni dünyalar, tehlikeli yolculuklar ve unutulmaz keşiflerle şekillenen macera serilerini keşfedin.'
            WHEN 'fantasy' THEN 'Büyülü dünyalar, efsanevi yaratıklar ve olağanüstü güçlerin yer aldığı fantastik serileri keşfedin.'
            WHEN 'urban-fantasy' THEN 'Modern şehir yaşamını büyü ve doğaüstü olaylarla birleştiren urban fantasy serilerini keşfedin.'
            WHEN 'sci-fi' THEN 'Gelecek teknolojileri, uzay yolculukları ve bilimsel fikirler üzerine kurulu bilim kurgu serilerini keşfedin.'
            WHEN 'cyberpunk' THEN 'Yüksek teknoloji, karanlık metropoller ve şirket egemenliği temalarını işleyen cyberpunk serilerini keşfedin.'
            WHEN 'romance' THEN 'Duygusal yakınlaşmaları, ilişkileri ve aşkın farklı hâllerini anlatan romantik serileri keşfedin.'
            WHEN 'drama' THEN 'Güçlü karakter çatışmaları ve duygusal dönüm noktalarıyla ilerleyen dram serilerini keşfedin.'
            WHEN 'comedy' THEN 'Eğlenceli karakterler, beklenmedik durumlar ve mizah dolu anlar sunan komedi serilerini keşfedin.'
            WHEN 'slice-of-life' THEN 'Gündelik yaşamın sıcak, sakin ve samimi anlarına odaklanan yaşamdan kesitler serilerini keşfedin.'
            WHEN 'mystery' THEN 'Gizemli olaylar, saklı ipuçları ve çözülmeyi bekleyen sırlarla ilerleyen serileri keşfedin.'
            WHEN 'thriller' THEN 'Yüksek gerilim, tehlike ve beklenmedik gelişmelerle okuru merakta bırakan serileri keşfedin.'
            WHEN 'horror' THEN 'Karanlık atmosferler, doğaüstü tehditler ve korku unsurları içeren serileri keşfedin.'
            WHEN 'psychological' THEN 'İnsan zihnini, iç çatışmaları ve karmaşık karakter motivasyonlarını inceleyen serileri keşfedin.'
            WHEN 'supernatural' THEN 'Ruhlar, lanetler ve gerçeküstü güçlerin gündelik dünyaya karıştığı serileri keşfedin.'
            WHEN 'historical' THEN 'Geçmiş dönemleri, tarihî olayları ve farklı kültürleri merkezine alan serileri keşfedin.'
            WHEN 'martial-arts' THEN 'Dövüş sanatları, disiplin ve ustalık yolculuğu üzerine kurulu mücadele serilerini keşfedin.'
            WHEN 'sports' THEN 'Rekabet, takım ruhu ve sporcuların gelişimini anlatan tempolu spor serilerini keşfedin.'
            WHEN 'mecha' THEN 'Dev robotlar, ileri teknoloji ve büyük ölçekli savaşların yer aldığı mecha serilerini keşfedin.'
            WHEN 'military' THEN 'Ordular, taktik kararlar ve savaş alanındaki mücadeleleri konu alan askerî serileri keşfedin.'
            WHEN 'school' THEN 'Okul hayatı, arkadaşlıklar ve genç karakterlerin gelişimi çevresinde ilerleyen serileri keşfedin.'
            WHEN 'ecchi' THEN 'Romantik komediyle hafif yetişkin mizahını birleştiren ecchi serilerini keşfedin.'
            WHEN 'harem' THEN 'Ana karakterin çevresindeki birden fazla romantik ilişki ihtimalini işleyen serileri keşfedin.'
            WHEN 'reverse-harem' THEN 'Kadın ana karakterin çevresindeki farklı romantik ilişkileri konu alan reverse harem serilerini keşfedin.'
            WHEN 'josei' THEN 'Yetişkin kadın okurlara yönelik gerçekçi ilişkiler ve yaşam deneyimleri sunan josei serilerini keşfedin.'
            WHEN 'seinen' THEN 'Olgun temalar, karmaşık karakterler ve derin anlatılar sunan seinen serilerini keşfedin.'
            WHEN 'shounen' THEN 'Gelişim, dostluk ve mücadele temalarıyla öne çıkan enerjik shounen serilerini keşfedin.'
            WHEN 'shoujo' THEN 'Duygusal ilişkiler ve karakter gelişimine odaklanan zarif shoujo serilerini keşfedin.'
            ELSE CONCAT(name, ' türündeki manga, manhwa, webtoon ve novel serilerini keşfedin.')
        END
    ),
    '$.icon',
    CASE slug
        WHEN 'action' THEN 'flame'
        WHEN 'adventure' THEN 'compass'
        WHEN 'fantasy' THEN 'sparkles'
        WHEN 'urban-fantasy' THEN 'building'
        WHEN 'sci-fi' THEN 'atom'
        WHEN 'cyberpunk' THEN 'cpu'
        WHEN 'romance' THEN 'heart'
        WHEN 'drama' THEN 'drama'
        WHEN 'comedy' THEN 'laugh'
        WHEN 'slice-of-life' THEN 'leaf'
        WHEN 'mystery' THEN 'search'
        WHEN 'thriller' THEN 'alarm'
        WHEN 'horror' THEN 'skull'
        WHEN 'psychological' THEN 'brain'
        WHEN 'supernatural' THEN 'ghost'
        WHEN 'historical' THEN 'landmark'
        WHEN 'martial-arts' THEN 'swords'
        WHEN 'sports' THEN 'trophy'
        WHEN 'mecha' THEN 'bot'
        WHEN 'military' THEN 'shield'
        WHEN 'school' THEN 'graduation'
        WHEN 'ecchi' THEN 'eye'
        WHEN 'harem' THEN 'users'
        WHEN 'reverse-harem' THEN 'user-heart'
        WHEN 'josei' THEN 'flower'
        WHEN 'seinen' THEN 'badge'
        WHEN 'shounen' THEN 'zap'
        WHEN 'shoujo' THEN 'flower'
        ELSE 'sparkles'
    END,
    '$.color',
    CASE slug
        WHEN 'action' THEN '#ef4444'
        WHEN 'adventure' THEN '#f59e0b'
        WHEN 'fantasy' THEN '#8b5cf6'
        WHEN 'urban-fantasy' THEN '#6366f1'
        WHEN 'sci-fi' THEN '#06b6d4'
        WHEN 'cyberpunk' THEN '#a855f7'
        WHEN 'romance' THEN '#ec4899'
        WHEN 'drama' THEN '#f97316'
        WHEN 'comedy' THEN '#eab308'
        WHEN 'slice-of-life' THEN '#22c55e'
        WHEN 'mystery' THEN '#64748b'
        WHEN 'thriller' THEN '#dc2626'
        WHEN 'horror' THEN '#7f1d1d'
        WHEN 'psychological' THEN '#7c3aed'
        WHEN 'supernatural' THEN '#4f46e5'
        WHEN 'historical' THEN '#a16207'
        WHEN 'martial-arts' THEN '#b91c1c'
        WHEN 'sports' THEN '#16a34a'
        WHEN 'mecha' THEN '#475569'
        WHEN 'military' THEN '#4d7c0f'
        WHEN 'school' THEN '#2563eb'
        WHEN 'ecchi' THEN '#db2777'
        WHEN 'harem' THEN '#d946ef'
        WHEN 'reverse-harem' THEN '#c026d3'
        WHEN 'josei' THEN '#be185d'
        WHEN 'seinen' THEN '#334155'
        WHEN 'shounen' THEN '#ea580c'
        WHEN 'shoujo' THEN '#f472b6'
        ELSE '#8b5cf6'
    END
)
WHERE type = 'genre';

UPDATE taxonomies
SET ui_config = JSON_SET(
    COALESCE(NULLIF(ui_config, ''), JSON_OBJECT()),
    '$.icon',
    CASE slug
        WHEN 'game-system' THEN 'gamepad'
        WHEN 'system' THEN 'cpu'
        WHEN 'leveling' THEN 'trending'
        WHEN 'level-up' THEN 'trending'
        WHEN 'skill-system' THEN 'scroll'
        WHEN 'status-window' THEN 'circle'
        WHEN 'dungeon' THEN 'door'
        WHEN 'tower' THEN 'building'
        WHEN 'raid' THEN 'target'
        WHEN 'op-protagonist' THEN 'crown'
        WHEN 'overpowered-mc' THEN 'crown'
        WHEN 'genius-mc' THEN 'lightbulb'
        WHEN 'weak-to-strong' THEN 'dumbbell'
        WHEN 'regression' THEN 'refresh'
        WHEN 'reincarnation' THEN 'repeat'
        WHEN 'time-travel' THEN 'hourglass'
        WHEN 'second-chance' THEN 'clock'
        WHEN 'transmigration' THEN 'orbit'
        WHEN 'isekai' THEN 'map'
        WHEN 'cultivation' THEN 'sprout'
        WHEN 'murim' THEN 'swords'
        WHEN 'martial-arts-tag' THEN 'swords'
        WHEN 'swordsmanship' THEN 'swords'
        WHEN 'necromancer' THEN 'skull'
        WHEN 'assassin' THEN 'target'
        WHEN 'magic-academy' THEN 'graduation'
        WHEN 'summoner' THEN 'wand'
        WHEN 'tamer' THEN 'paw'
        WHEN 'alchemy' THEN 'atom'
        WHEN 'blacksmith' THEN 'anvil'
        WHEN 'demons' THEN 'flame'
        WHEN 'angels' THEN 'sparkles'
        WHEN 'gods' THEN 'star'
        WHEN 'dragons' THEN 'flame'
        WHEN 'monsters' THEN 'axe'
        WHEN 'vampires' THEN 'dna'
        WHEN 'werewolves' THEN 'paw'
        WHEN 'survival' THEN 'shield'
        WHEN 'revenge' THEN 'swords'
        WHEN 'betrayal' THEN 'heart-crack'
        WHEN 'political' THEN 'landmark'
        WHEN 'kingdom-building' THEN 'castle'
        WHEN 'empire' THEN 'crown'
        WHEN 'war' THEN 'shield'
        WHEN 'post-apocalyptic' THEN 'cloud'
        WHEN 'magic' THEN 'wand'
        WHEN 'elemental-powers' THEN 'waves'
        WHEN 'superpowers' THEN 'zap'
        WHEN 'system-admin' THEN 'cpu'
        WHEN 'virtual-reality' THEN 'eye'
        WHEN 'vrmmo' THEN 'gamepad'
        WHEN 'video-games' THEN 'gamepad'
        WHEN 'love-triangle' THEN 'heart'
        WHEN 'slow-burn' THEN 'flame'
        WHEN 'enemies-to-lovers' THEN 'heart-crack'
        WHEN 'childhood-friends' THEN 'users'
        WHEN 'contract-marriage' THEN 'scroll'
        WHEN 'marriage-of-convenience' THEN 'scale'
        WHEN 'harem' THEN 'users'
        WHEN 'reverse-harem' THEN 'user-heart'
        WHEN 'dark-fantasy' THEN 'ghost'
        WHEN 'tragedy' THEN 'drama'
        WHEN 'psychological-trauma' THEN 'brain'
        WHEN 'mind-games' THEN 'brain'
        WHEN 'antihero' THEN 'mask'
        WHEN 'villain-protagonist' THEN 'skull'
        WHEN 'school-life' THEN 'graduation'
        WHEN 'academy' THEN 'landmark'
        WHEN 'office-romance' THEN 'building'
        WHEN 'age-gap' THEN 'clock'
        WHEN 'gender-bender' THEN 'repeat'
        WHEN 'crossdressing' THEN 'mask'
        WHEN 'mecha-combat' THEN 'bot'
        WHEN 'military-strategy' THEN 'map'
        WHEN 'space-opera' THEN 'rocket'
        WHEN 'cyberpunk-elements' THEN 'cpu'
        WHEN 'ai' THEN 'bot'
        WHEN 'robots' THEN 'bot'
        WHEN 'cooking' THEN 'chef'
        WHEN 'crafting' THEN 'hammer'
        WHEN 'farming' THEN 'sprout'
        WHEN 'merchant' THEN 'coins'
        WHEN 'healer' THEN 'hand-heart'
        ELSE 'sparkles'
    END,
    '$.color',
    CASE slug
        WHEN 'game-system' THEN '#6366f1'
        WHEN 'system' THEN '#475569'
        WHEN 'leveling' THEN '#22c55e'
        WHEN 'level-up' THEN '#22c55e'
        WHEN 'skill-system' THEN '#0ea5e9'
        WHEN 'status-window' THEN '#64748b'
        WHEN 'dungeon' THEN '#475569'
        WHEN 'tower' THEN '#f59e0b'
        WHEN 'raid' THEN '#ef4444'
        WHEN 'op-protagonist' THEN '#dc2626'
        WHEN 'overpowered-mc' THEN '#dc2626'
        WHEN 'genius-mc' THEN '#eab308'
        WHEN 'weak-to-strong' THEN '#16a34a'
        WHEN 'regression' THEN '#f97316'
        WHEN 'reincarnation' THEN '#10b981'
        WHEN 'time-travel' THEN '#06b6d4'
        WHEN 'second-chance' THEN '#3b82f6'
        WHEN 'transmigration' THEN '#8b5cf6'
        WHEN 'isekai' THEN '#14b8a6'
        WHEN 'cultivation' THEN '#ca8a04'
        WHEN 'murim' THEN '#991b1b'
        WHEN 'martial-arts-tag' THEN '#991b1b'
        WHEN 'swordsmanship' THEN '#334155'
        WHEN 'necromancer' THEN '#581c87'
        WHEN 'assassin' THEN '#be123c'
        WHEN 'magic-academy' THEN '#4f46e5'
        WHEN 'summoner' THEN '#0891b2'
        WHEN 'tamer' THEN '#0d9488'
        WHEN 'alchemy' THEN '#d97706'
        WHEN 'blacksmith' THEN '#57534e'
        WHEN 'demons' THEN '#b91c1c'
        WHEN 'angels' THEN '#38bdf8'
        WHEN 'gods' THEN '#eab308'
        WHEN 'dragons' THEN '#dc2626'
        WHEN 'monsters' THEN '#4b5563'
        WHEN 'vampires' THEN '#9f1239'
        WHEN 'werewolves' THEN '#6b7280'
        WHEN 'survival' THEN '#65a30d'
        WHEN 'revenge' THEN '#e11d48'
        WHEN 'betrayal' THEN '#7c2d12'
        WHEN 'political' THEN '#64748b'
        WHEN 'kingdom-building' THEN '#2563eb'
        WHEN 'empire' THEN '#78350f'
        WHEN 'war' THEN '#b91c1c'
        WHEN 'post-apocalyptic' THEN '#44403c'
        WHEN 'magic' THEN '#7c3aed'
        WHEN 'elemental-powers' THEN '#0284c7'
        WHEN 'superpowers' THEN '#f59e0b'
        WHEN 'system-admin' THEN '#475569'
        WHEN 'virtual-reality' THEN '#7c3aed'
        WHEN 'vrmmo' THEN '#4f46e5'
        WHEN 'video-games' THEN '#6366f1'
        WHEN 'love-triangle' THEN '#f59e0b'
        WHEN 'slow-burn' THEN '#fb7185'
        WHEN 'enemies-to-lovers' THEN '#e11d48'
        WHEN 'childhood-friends' THEN '#3b82f6'
        WHEN 'contract-marriage' THEN '#6d28d9'
        WHEN 'marriage-of-convenience' THEN '#57534e'
        WHEN 'harem' THEN '#d97706'
        WHEN 'reverse-harem' THEN '#db2777'
        WHEN 'dark-fantasy' THEN '#312e81'
        WHEN 'tragedy' THEN '#be123c'
        WHEN 'psychological-trauma' THEN '#4c1d95'
        WHEN 'mind-games' THEN '#475569'
        WHEN 'antihero' THEN '#1f2937'
        WHEN 'villain-protagonist' THEN '#7f1d1d'
        WHEN 'school-life' THEN '#2563eb'
        WHEN 'academy' THEN '#0891b2'
        WHEN 'office-romance' THEN '#9333ea'
        WHEN 'age-gap' THEN '#d97706'
        WHEN 'gender-bender' THEN '#8b5cf6'
        WHEN 'crossdressing' THEN '#475569'
        WHEN 'mecha-combat' THEN '#2563eb'
        WHEN 'military-strategy' THEN '#3f6212'
        WHEN 'space-opera' THEN '#0284c7'
        WHEN 'cyberpunk-elements' THEN '#9333ea'
        WHEN 'ai' THEN '#2563eb'
        WHEN 'robots' THEN '#0891b2'
        WHEN 'cooking' THEN '#ea580c'
        WHEN 'crafting' THEN '#78716c'
        WHEN 'farming' THEN '#16a34a'
        WHEN 'merchant' THEN '#ca8a04'
        WHEN 'healer' THEN '#10b981'
        ELSE '#8b5cf6'
    END
)
WHERE type = 'tag';
