import React from 'react';
import {
  AlarmClock,
  Anvil,
  Atom,
  Axe,
  Badge,
  Bot,
  Brain,
  Building2,
  Castle,
  ChefHat,
  CircleDot,
  Clock3,
  CloudLightning,
  Coins,
  Compass,
  Cpu,
  Crown,
  Dna,
  DoorOpen,
  Drama,
  Dumbbell,
  Eye,
  Factory,
  Flame,
  Flower2,
  Gamepad2,
  Gem,
  Ghost,
  GraduationCap,
  Hammer,
  HandHeart,
  Heart,
  HeartCrack,
  Hourglass,
  Landmark,
  Laugh,
  Leaf,
  Lightbulb,
  LucideIcon,
  Map,
  Orbit,
  PawPrint,
  Pickaxe,
  RefreshCw,
  Repeat2,
  Rocket,
  Scale,
  ScrollText,
  Search,
  Shield,
  Skull,
  Sparkles,
  Sprout,
  Star,
  Swords,
  Target,
  Telescope,
  TrendingUp,
  Trophy,
  Users,
  VenetianMask,
  WandSparkles,
  Waves,
  Zap,
} from 'lucide-react';

const icons: Record<string, LucideIcon> = {
  alarm: AlarmClock,
  anvil: Anvil,
  atom: Atom,
  axe: Axe,
  badge: Badge,
  bot: Bot,
  brain: Brain,
  building: Building2,
  castle: Castle,
  chef: ChefHat,
  circle: CircleDot,
  clock: Clock3,
  cloud: CloudLightning,
  coins: Coins,
  compass: Compass,
  cpu: Cpu,
  crown: Crown,
  dna: Dna,
  door: DoorOpen,
  drama: Drama,
  dumbbell: Dumbbell,
  eye: Eye,
  factory: Factory,
  flame: Flame,
  flower: Flower2,
  gamepad: Gamepad2,
  gem: Gem,
  ghost: Ghost,
  graduation: GraduationCap,
  hammer: Hammer,
  'hand-heart': HandHeart,
  heart: Heart,
  'heart-crack': HeartCrack,
  hourglass: Hourglass,
  landmark: Landmark,
  laugh: Laugh,
  leaf: Leaf,
  lightbulb: Lightbulb,
  map: Map,
  orbit: Orbit,
  paw: PawPrint,
  pickaxe: Pickaxe,
  refresh: RefreshCw,
  repeat: Repeat2,
  rocket: Rocket,
  scale: Scale,
  scroll: ScrollText,
  search: Search,
  shield: Shield,
  skull: Skull,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  swords: Swords,
  target: Target,
  telescope: Telescope,
  trending: TrendingUp,
  trophy: Trophy,
  'user-heart': HandHeart,
  users: Users,
  mask: VenetianMask,
  wand: WandSparkles,
  waves: Waves,
  zap: Zap,
};

export const taxonomyColor = (color?: unknown): string =>
  typeof color === 'string' && /^#[0-9a-f]{6}$/i.test(color) ? color : '#8b5cf6';

export const TaxonomyIcon: React.FC<{
  name?: unknown;
  className?: string;
}> = ({ name, className }) => {
  const Icon = typeof name === 'string' ? icons[name] || Sparkles : Sparkles;
  return <Icon aria-hidden="true" className={className} />;
};
